import React from 'react';

import MultipleChoiceQuestion from 'components/multiple-choice-question/multiple-choice-question';

export default [
  // English to Spanish
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="Hello!" possibleAnswers={['¡Tarde!', '¡Adios!', '¡Hola!']} correctAnswer="¡Hola!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="How are you?" possibleAnswers={['¿Qué tal?', '¿Cómo te va?', '¿Cómo te llamas?']} correctAnswer="¿Qué tal?" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="See you later!" possibleAnswers={['¡Estoy bien!', '¡Hasta la vista!', '¡De nada!']} correctAnswer="¡Hasta la vista!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="You're welcome!" possibleAnswers={['¡Estoy bien!', '¡Hasta la vista!', '¡De nada!']} correctAnswer="¡De nada!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="Where is the bathroom?" possibleAnswers={['¿Dónde está el baño?', '¡Hasta la vista!', '¿De nada?']} correctAnswer="¡De nada!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  // Spanish to English
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="Yo no comprendo español." possibleAnswers={['I know Spanish', 'I know some Spanish', 'I don\'t understand Spanish']} correctAnswer="I don't understand Spanish" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="Necesito ayuda." possibleAnswers={['I need help', 'I\'m going home', 'I don\'t need anything else']} correctAnswer="I need help" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="¿Puede hablar más despacio, por favor?" possibleAnswers={['Can you do me a favour, please?', 'Can you help me, please?', 'Can you speak slowly, please?']} correctAnswer="Can you speak slowly, please?" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="¡Salud!" possibleAnswers={['Thanks!', 'Stop!', 'Cheers!']} correctAnswer="Cheers!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
  <MultipleChoiceQuestion questionTitle="Mark the correct meaning" questionText="¡Buen Provecho!" possibleAnswers={['Genius!', 'Great!', 'Well done!']} correctAnswer="Well done!" buttonText="Check Result" correctResultTitle="Correct Result!" correctResultText="Well Done." incorrectResultTitle="Incorrect. Correct Result is:" incorrectResultText="" />,
];
