export default {
  colors: {
    correctBannerBackground: '#b8f28b',
    incorrectBannerBackground: '#ffc1c1',
    undecidedBannerBackground: '#f5f5f5',
    text: '#323c41',
    activeLabelBackground: '#ddf4ff',
    activeLabelBorder: '#1cb0f6',
    labelHover: '#f7f7f7',
    labelBorder: '#e5e5e5',
    labelBackground: '#ffffff',
    iconBackground: '#ffffff',
    textAreaBackground: '#ffffff',
    textAreaBorder: '#e5e5e5',
    buttonBackground: '#e5e5e5',
    buttonBorder: '#323c41',
    activeButtonBackground: '#b8f28b',
    activeButtonBorder: '#78c800',
    activeButtonHover: '#84dc00',
  },
};
