module.exports = [{
  label: 'Image',
  url: 'http://localhost:3000/?component=Image',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'ImageBanner',
  url: 'http://localhost:3000/?component=ImageBanner',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'MultipleChoiceQuestion-1',
  url: 'http://localhost:3000/?component=MultipleChoiceQuestion-1',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'MultipleChoiceQuestion-2',
  url: 'http://localhost:3000/?component=MultipleChoiceQuestion-2',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'ResultBanner-1',
  url: 'http://localhost:3000/?component=ResultBanner-1',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'ResultBanner-2',
  url: 'http://localhost:3000/?component=ResultBanner-2',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'ResultBanner-3',
  url: 'http://localhost:3000/?component=ResultBanner-3',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'TextArea-1',
  url: 'http://localhost:3000/?component=TextArea-1',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'TextArea-2',
  url: 'http://localhost:3000/?component=TextArea-2',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'ChallengeHeader',
  url: 'http://localhost:3000/?component=ChallengeHeader',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'TranslateTextQuestion',
  url: 'http://localhost:3000/?component=TranslateTextQuestion',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'Label-1',
  url: 'http://localhost:3000/?component=Label-1',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'Label-2',
  url: 'http://localhost:3000/?component=Label-2',
  selectors: ['#root'],
  hoverSelector: '#root > div',
  misMatchThreshold: 0,
}, {
  label: 'Label-3',
  url: 'http://localhost:3000/?component=Label-3',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'Label-4',
  url: 'http://localhost:3000/?component=Label-4',
  selectors: ['#root'],
  misMatchThreshold: 0,
}, {
  label: 'Label-5',
  url: 'http://localhost:3000/?component=Label-5',
  selectors: ['#root'],
  hoverSelector: '#root > div',
  misMatchThreshold: 0,
}, {
  label: 'Label-6',
  url: 'http://localhost:3000/?component=Label-6',
  selectors: ['#root'],
  misMatchThreshold: 0,
}];
